### ISSUE TITLE
where max-ws comes from?

### ISSUE THREAD

**Issue by walkerwzy** [maxep/max-ws#1]
in bin/ directory, there's only a maxb file, and when I use `maxb` take place the command `max-ws`, get this error: `Unsupported major.minor version 52.0`, 

my version:

```
walkers-MacBook-Pro:bin walker$ java -version
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)
```

**Comment by walkerwzy** [comment]
are my JDK version too higher or too lower? or some other reason?

**Comment by maxep** [comment]
The bin directory of [max-ws 0.7.0](https://github.com/maxep/max-ws/releases/tag/v0.7.0) contains 2 files : max-ws and max-ws.bat. Or you sure you didn't mix up with [maxb 0.7.0](https://github.com/maxep/maxb/releases/tag/v0.7.0) ?

Anyway, your java version is too low, you need java 1.8

**Comment by walkerwzy** [comment]
1, I clicked the link under `Version History` section, and it lead me to the `maxb` download page, and where can I find the `max-ws` download right download link in the readme file?
2, when I use the right bin file and the 1.8JDK,  it worked.

**Comment by maxep** [comment]
Hi @walkerwzy 

My bad, actually I mixed it up in the readme. I gave you the link to max-ws in my previous comment, It's available in the [releases section](https://github.com/maxep/max-ws/releases).
