### ISSUE TITLE
Generating wsdl file in Objc code exports code with class extension in Java style.

### ISSUE THREAD

**Issue by IuliuMoga** [maxep/max-ws#2]
The generator works fine without errors but the generated ObjC code contains extended classes declarations as Java style.

-the call of the generator in Terminal on Services.wsdl (is an Exchange 2013 EWS .wsdl file) is:
max-ws-0.7.0/bin/max-ws "-pico" "-prefix" "Ews_" "Services.wsdl"

-it generates:
@class Ews_JAXBElement<? extends SearchExpressionType>;

-or classes with function bodys:

```
#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Ews_ArrayOfResponseMessagesType.h"

@implementation Ews_ArrayOfResponseMessagesType

@synthesize createItemResponseMessageOrDeleteItemResponseMessageOrGetItemResponseMessage = _createItemResponseMessageOrDeleteItemResponseMessageOrGetItemResponseMessage;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];

    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"createItemResponseMessageOrDeleteItemResponseMessageOrGetItemResponseMessage" propertyName:@"createItemResponseMessageOrDeleteItemResponseMessageOrGetItemResponseMessage" type:PICO_TYPE_OBJECT clazz:[Ews_JAXBElement<? extends ResponseMessageType> class]];
    [map setObject:ps forKey:@"createItemResponseMessageOrDeleteItemResponseMessageOrGetItemResponseMessage"];

    return map;
}

@end
```

Thanks!

**Comment by maxep** [comment]
Please refer to [this](https://github.com/bulldog2011/mwsc/wiki/FAQ).

**Comment by IuliuMoga** [comment]
@maxep Thanks for your support, I will try this later!
Have a nice day!

**Comment by IuliuMoga** [comment]
@maxep Hy! I've tried today and still the same problem occurs.

```
<jaxb:bindings version="2.0"
    xmlns:jaxb="http://java.sun.com/xml/ns/jaxb">
    <jaxb:bindings>
        <jaxb:globalBindings generateElementProperty="false"/>
    </jaxb:bindings>
</jaxb:bindings>
```

And the command line is:
max-ws-0.7.0/bin/max-ws -pico -prefix Ews_ -b binding.xjb services.wsdl

Thanks again for your support and patience!

**Comment by maxep** [comment]
Hi @IuliuMoga 

It's hard to tell without seeing the wsdl. Have you check the current limitation?:
1. Only Document/Literal style WSDL is support, RPC style wsdl is not supported
2. Only single target namespace is supported(please specify target package if your wsdl contains multiple namespaces)
3. Xsd nest anonymous type is only experimentally supported and is not recommended to use.
4. Xsd:choice is not supported and will be ignored if presents
5. Xsd any attribute is not supported

**Comment by IuliuMoga** [comment]
@maxep 
It's hard to tell i'm not a knower of xml files it this helps I've attached the xml's files that im using in this link.

http://www.filedropper.com/wsdl

Thanks again!

**Comment by maxep** [comment]
Your wsdl contains abstract types as well as xs:choice types and it is not currently supported by the generator...

**Comment by IuliuMoga** [comment]
@maxep Thank you for response,
One last question: I was wondering if I could write manualy the routines that cannot be generated, maybe  encapsulate it in one or few functions?

**Comment by maxep** [comment]
Hi @IuliuMoga 

Your wsdl is quite complex and this generator is not well adapted for it. You can try to focus on the endpoints and types you need and fix it manually, but it will still be a complex rework.
